CONN_BUFFER_SIZE = 4096
DEFAULT_ADDR = "0.0.0.0"
DEFAULT_PORT = 5279
GROWATT_SERVER_ADDR = "server.growatt.com"
GROWATT_SERVER_PORT = 5279
SERVER_MAX_CONN = 200

GROWATT_MASK = "Growatt"
GROWATT_MASK_HEX = ["{:02x}".format(ord(x)) for x in GROWATT_MASK]
GROWATT_MASK_LEN = len(GROWATT_MASK_HEX)

HEADER_BYTES_SLICE = slice(0, 8)

PROTOCOL_MSG_SLICE = slice(6, 8)
MSG_TYPE_SLICE = slice(14, 16)
